# version: '3.8'

services:
  flask_app:
    build: .
    container_name: flask_api
    restart: always
    depends_on:
      - mysql
      - redis
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - .:/app
      - ./logs:/app/logs 
    healthcheck:
        disable: true
      # test: ["CMD", "curl", "-f", "http://localhost:5000/api/tasks/test"]
      # interval: 10s
      # timeout: 5s
      # retries: 3

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 3366
      MYSQL_DATABASE: my_project_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
        disable: true
      # test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      # interval: 10s
      # timeout: 5s
      # retries: 3

  redis:
    image: redis:7
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
        disable: true
      # test: ["CMD", "redis-cli", "ping"]
      # interval: 10s
      # timeout: 5s
      # retries: 3

volumes:
  mysql_data:
  redis_data: