# version: '3.8'

services:
  web:
    build: .
    container_name: web
    restart: always
    depends_on:
      - mysql
      - redis
    ports:
      - "8000:8000"  # Dùng expose thay vì ports để tránh public
    env_file:
      - .env
    volumes:
      - .:/app
      - ./logs:/app/logs 
    healthcheck:
      disable: true
      # test: ["CMD", "curl", "-f", "http://localhost:5000/api/tasks/test"]
      # interval: 10s
      # timeout: 5s
      # retries: 3
    

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: NAwqxDAzavyWecquJRohCNRqBVjajVPY
      MYSQL_DATABASE: railway
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      disable: true
      # test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      # interval: 10s
      # timeout: 5s
      # retries: 3

  redis:
    image: redis:7
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      disable: true
      # test: ["CMD", "redis-cli", "ping"]
      # interval: 10s
      # timeout: 5s
      # retries: 3

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    depends_on:
      - web
    ports:
      - "80:80"  # Chạy trên cổng 80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  mysql_data:
  redis_data: