"""fix migration

Revision ID: 19422a2e3794
Revises: 9b6429b94e8f
Create Date: 2025-03-18 14:19:33.161813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19422a2e3794'
down_revision = '9b6429b94e8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access_token', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('access_token')

    # ### end Alembic commands ###
