name: Run Tests

# Trigger workflow khi push hoặc pull request vào branch main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest # Hệ điều hành để chạy job, bạn có thể thay đổi nếu cần

    steps:
      # Checkout code từ repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Cài đặt môi trường (ví dụ: Node.js, Python, tùy ngôn ngữ bạn dùng)
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # Thay đổi phiên bản nếu cần

      # Cài đặt dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      # Chạy test
      - name: Run Tests
        run:  pytest app/tests/unit/test_routes_unit.py # Thay bằng lệnh chạy test của bạn, ví dụ: pytest, ./gradlew test
        env:
          SQLALCHEMY_DATABASE_URI: "sqlite:///:memory:" # Dùng SQLite in-memory
          FLASK_ENV: testing
          JWT_SECRET_KEY: "super-secret_key"
          SECRET_KEY: "super-secret_key"
